[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "../lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }
fs_permissions = [{ access = "read", path = "./" }]

# Remappings
remappings = [
    "uniswap-hooks/=../lib/uniswap-hooks/src/",
    "v4-core/=../lib/v4-core/src/",
    "@openzeppelin/contracts/=../lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "forge-std/=../lib/v4-core/lib/forge-std/src/"
]

[rpc_endpoints]
shardeum = "https://api-unstable.shardeum.org"

[etherscan]
shardeum = { key = "${SHARDEUM_API_KEY}", url = "https://explorer-unstable.shardeum.org/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
